In [ ]:
# Question 1 Solution using np.array()
import pandas as pd
import numpy as np

data = pd.read_csv("staff_data.csv")

emp_ages = np.array(data["emp_age"])
emp_salary = np.array(data["emp_salary"])

# Emp ages
print("Emp ages:")
print(emp_ages)
print(f"Data Type: {emp_ages.dtype}")
print(f"Dimension: {emp_ages.ndim}")
print(f"Shape: {emp_ages.shape}")
print(f"Size: {emp_ages.size}")

print("")

# Emp salary
print("Emp salary:")
print(emp_salary)
print(f"Data Type: {emp_salary.dtype}")
print(f"Dimension: {emp_salary.ndim}")
print(f"Shape: {emp_salary.shape}")
print(f"Size: {emp_salary.size}")

Emp ages:
[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Data Type: int64
Dimension: 1
Shape: (50,)
Size: 50


Emp salary:
[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]
Data Type: int64
Dimension: 1
Shape: (50,)
Size: 50

In [28]:
# Answer to the question 2
max_emp_salary = np.max(emp_salary)
print(max_emp_salary)

min_emp_salary = np.min(emp_salary)
print(min_emp_salary)

average_emp_salary = np.mean(emp_salary)
print(average_emp_salary)

avg_emp_age=np.mean(emp_ages)
print(avg_emp_age)

94722
35452
68409.48
35.44

In [ ]:
new_ages = emp_ages[(emp_ages >= 25) & (emp_ages <= 40) & (emp_salary > 50000)]
new_salary = emp_salary[(emp_ages >= 25) & (emp_ages <= 40) & (emp_salary > 50000)]

print("Ages:")
print(new_ages)
print("")

print("Salaries:")
print(new_salary)
print("")

print("Number of employees:")
print(len(new_salary))

Ages:
[37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]

Salaries:
[72187 58915 92864 90494 68641 56879 83682 94722 74146 78354 79898 59682
 73700 84188 52013 63326 59727]

Number of employees:
17

In [34]:
avg_emp_age=np.mean(emp_ages)
print(f"average age is {avg_emp_age}")

arr_copy = np.copy(emp_ages)

arr_copy[arr_copy>= avg_emp_age] += 2
arr_copy[arr_copy< avg_emp_age] += 4

print("Original Ages:")
print(emp_ages)
print("")

print("Modified Ages:")
print(arr_copy)

average age is 35.44
Original Ages:
[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]

Modified Ages:
[56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]

In [39]:
roles = np.array(data["role"])

techrole = (roles == "Software Developer") | (roles == "Backend Developer")

emp_salary_float = emp_salary.astype(float)

old_total = np.sum(emp_salary_float[techrole])

new_emp_salary = emp_salary_float.copy()
new_emp_salary[techrole] *= 1.08

new_total = np.sum(new_emp_salary[techrole])

increase = new_total - old_total

print("Old Total Salary:")
print(old_total)
print("")

print("New Total Salary:")
print(new_total)
print("")

print("Increase Expense:")
print(increase)

Old Total Salary:
872150.0

New Total Salary:
941922.0

Increase Expense:
69772.0

In [40]:
# pandas

import pandas as pd

df = pd.read_csv('staff_data.csv')
print(df)

    emp_id  emp_age  emp_salary                 role
0      101       54       51725           HR Manager
1      102       23       38495           Accountant
2      103       20       35452   Operations Manager
3      104       43       82295     Digital Marketer
4      105       37       72187    Backend Developer
5      106       37       58915           HR Manager
6      107       21       76159    Backend Developer
7      108       35       92864      Sales Executive
8      109       24       76155      Sales Executive
9      110       38       90494         HR Executive
10     111       31       68641    Backend Developer
11     112       35       48079  Marketing Executive
12     113       29       56879      Sales Executive
13     114       38       83682   Operations Manager
14     115       27       94722     Digital Marketer
15     116       45       91041    Financial Analyst
16     117       51       48899      Sales Executive
17     118       48       68744   Operations Manager
18     119       20       63187   Software Developer
19     120       32       74146    Backend Developer
20     121       51       75641      Sales Executive
21     122       53       47678      Sales Executive
22     123       21       76760           Accountant
23     124       26       78354   Software Developer
24     125       53       60584         HR Executive
25     126       37       79898   Operations Manager
26     127       26       59682     Digital Marketer
27     128       21       71888         HR Executive
28     129       45       51086   Software Developer
29     130       30       73700           Accountant
30     131       20       82550      Sales Executive
31     132       47       71447  Marketing Executive
32     133       53       76100     Digital Marketer
33     134       53       72269    Backend Developer
34     135       23       73314   Software Developer
35     136       24       87428   Software Developer
36     137       21       94427      Sales Executive
37     138       30       84188           Accountant
38     139       27       52013           HR Manager
39     140       25       63326      Sales Executive
40     141       39       44396  Marketing Executive
41     142       20       59500     Digital Marketer
42     143       47       55523         HR Executive
43     144       41       58602           Accountant
44     145       22       90794         HR Executive
45     146       52       41061           HR Manager
46     147       42       82331   Software Developer
47     148       54       73048   Software Developer
48     149       31       59727     Digital Marketer
49     150       50       50398  Marketing Executive

In [ ]:
df.head(3)

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

In [58]:
newdf = df.copy()
# print(newdf)

newdf = newdf[["emp_id", "emp_age", "role"]]

df = df[df["role"].str.contains("HR")]

print(f"Total HR {len(df)}")
print(df)

Total HR 9
    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager

In [ ]:
newdf = df.copy()

newdf = newdf.sort_values(
    by=["emp_age", "emp_salary"],
    ascending=[True, False]
)

newdf = newdf[["emp_id", "emp_salary", "role"]]
newdf.head(5)

    emp_id  emp_salary          role
27     128       71888  HR Executive
44     145       90794  HR Executive
38     139       52013    HR Manager
5      106       58915    HR Manager
9      110       90494  HR Executive

In [68]:
df["previous_salary"] = df["emp_salary"]
df["new_salary"] = df["previous_salary"]

techroles = (df["role"] == "Software Developer") | (df["role"] == "Backend Developer")

non_techroles = (df["role"] != "Software Developer") & (df["role"] != "Backend Developer")


df.loc[techroles, "new_salary"] = df["previous_salary"] * 1.12

df.loc[non_techroles, "new_salary"] = df["previous_salary"] * 1.05

df["increase_of_salary"] = df["new_salary"] - df["previous_salary"]


print("Roles:")
print(df["role"])
print("")

print("Previous Salary:")
print(df["previous_salary"])
print("")

print("New Salary:")
print(df["new_salary"])
print("")

print("Increase Salary:")
print(df["increase_of_salary"])

Roles:
0       HR Manager
5       HR Manager
9     HR Executive
24    HR Executive
27    HR Executive
38      HR Manager
42    HR Executive
44    HR Executive
45      HR Manager
Name: role, dtype: object

Previous Salary:
0     51725
5     58915
9     90494
24    60584
27    71888
38    52013
42    55523
44    90794
45    41061
Name: previous_salary, dtype: int64

New Salary:
0     54311.25
5     61860.75
9     95018.70
24    63613.20
27    75482.40
38    54613.65
42    58299.15
44    95333.70
45    43114.05
Name: new_salary, dtype: float64

Increase Salary:
0     2586.25
5     2945.75
9     4524.70
24    3029.20
27    3594.40
38    2600.65
42    2776.15
44    4539.70
45    2053.05
Name: increase_of_salary, dtype: float64

C:\Users\Avff\AppData\Local\Temp\ipykernel_1952\2322896163.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[54311.25 61860.75 95018.7  63613.2  75482.4  54613.65 58299.15 95333.7
 43114.05]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[non_techroles, "new_salary"] = df["previous_salary"] * 1.05